"""add deep player research synthesis

Revision ID: 0013_deep_player_research_synthesis
Revises: 0012_evidence_bundles_dimension_confidence
"""
from alembic import op
import sqlalchemy as sa
revision="0013_deep_player_research_synthesis"; down_revision="0012_evidence_bundles_dimension_confidence"; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("research_deep_runs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("thread_id",sa.String(36),sa.ForeignKey("research_threads.id",ondelete="CASCADE"),nullable=False),sa.Column("player_id",sa.Integer(),sa.ForeignKey("players.id",ondelete="RESTRICT"),nullable=False),sa.Column("situation_id",sa.String(36),sa.ForeignKey("research_situations.id",ondelete="SET NULL")),sa.Column("trigger_id",sa.String(36),sa.ForeignKey("player_research_triggers.id",ondelete="SET NULL")),sa.Column("research_cutoff",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("target_dimensions",sa.JSON(),nullable=False),sa.Column("discovery_execution_id",sa.String(36),sa.ForeignKey("research_discovery_executions.id",ondelete="SET NULL")),sa.Column("orchestration_version",sa.String(64),nullable=False),sa.Column("failure_reason",sa.Text()),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("status IN ('pending', 'running', 'research_complete', 'blind_spot_complete', 'completed', 'partial', 'failed')",name="ck_research_deep_runs_status"))
    op.create_index("ix_research_deep_runs_player_cutoff","research_deep_runs",["player_id","research_cutoff"]);op.create_index("ix_research_deep_runs_thread_id","research_deep_runs",["thread_id"]);op.create_index("ix_research_deep_runs_status","research_deep_runs",["status"])
    op.create_table("research_deep_run_assessments",sa.Column("deep_run_id",sa.String(36),sa.ForeignKey("research_deep_runs.id",ondelete="CASCADE"),primary_key=True),sa.Column("dimension_assessment_id",sa.String(36),sa.ForeignKey("research_dimension_assessments.id",ondelete="RESTRICT"),primary_key=True));op.create_table("research_deep_run_quality_runs",sa.Column("deep_run_id",sa.String(36),sa.ForeignKey("research_deep_runs.id",ondelete="CASCADE"),primary_key=True),sa.Column("quality_run_id",sa.String(36),sa.ForeignKey("research_quality_runs.id",ondelete="RESTRICT"),primary_key=True))
    op.create_table("research_blind_spot_findings",sa.Column("id",sa.String(36),primary_key=True),sa.Column("deep_run_id",sa.String(36),sa.ForeignKey("research_deep_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("dimension",sa.String(64)),sa.Column("category",sa.String(64),nullable=False),sa.Column("question",sa.Text(),nullable=False),sa.Column("why_it_matters",sa.Text(),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("resolution_summary",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("status IN ('open', 'researched', 'unresolved')",name="ck_research_blind_spot_findings_status"));op.create_index("ix_research_blind_spot_findings_run_status","research_blind_spot_findings",["deep_run_id","status"])
    op.create_table("research_blind_spot_finding_evidence",sa.Column("finding_id",sa.String(36),sa.ForeignKey("research_blind_spot_findings.id",ondelete="CASCADE"),primary_key=True),sa.Column("evidence_id",sa.String(36),sa.ForeignKey("research_evidence.id",ondelete="RESTRICT"),primary_key=True))
    op.create_table("research_player_syntheses",sa.Column("id",sa.String(36),primary_key=True),sa.Column("deep_run_id",sa.String(36),sa.ForeignKey("research_deep_runs.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("thread_id",sa.String(36),sa.ForeignKey("research_threads.id",ondelete="CASCADE"),nullable=False),sa.Column("player_id",sa.Integer(),sa.ForeignKey("players.id",ondelete="RESTRICT"),nullable=False),sa.Column("situation_id",sa.String(36),sa.ForeignKey("research_situations.id",ondelete="SET NULL")),sa.Column("research_cutoff",sa.DateTime(timezone=True),nullable=False),sa.Column("overall_research_state",sa.String(16),nullable=False),sa.Column("executive_summary",sa.Text(),nullable=False),sa.Column("dimension_summaries",sa.JSON(),nullable=False),sa.Column("key_strengths",sa.JSON(),nullable=False),sa.Column("key_risks",sa.JSON(),nullable=False),sa.Column("contradictions",sa.JSON(),nullable=False),sa.Column("missing_information",sa.JSON(),nullable=False),sa.Column("future_monitoring",sa.JSON(),nullable=False),sa.Column("prompt_version",sa.String(64),nullable=False),sa.Column("model_metadata",sa.JSON()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("overall_research_state IN ('clear', 'mixed', 'thin', 'unresolved')",name="ck_research_player_syntheses_state"));op.create_index("ix_research_player_syntheses_player_cutoff","research_player_syntheses",["player_id","research_cutoff"])
def downgrade():
    op.drop_table("research_player_syntheses");op.drop_table("research_blind_spot_finding_evidence");op.drop_table("research_blind_spot_findings");op.drop_table("research_deep_run_quality_runs");op.drop_table("research_deep_run_assessments");op.drop_table("research_deep_runs")
