"""add weekly research orchestration

Revision ID: 0014_weekly_research_orchestration
Revises: 0013_deep_player_research_synthesis
"""
from alembic import op
import sqlalchemy as sa
revision="0014_weekly_research_orchestration"; down_revision="0013_deep_player_research_synthesis"; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("research_cycles",sa.Column("id",sa.String(36),primary_key=True),sa.Column("gameweek",sa.Integer(),nullable=False),sa.Column("research_cutoff",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("max_deep_runs",sa.Integer(),nullable=False),sa.Column("orchestration_version",sa.String(64),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("prepared_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("failure_reason",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("status IN ('pending','monitoring','prepared','executing','completed','partial','failed')",name="ck_research_cycles_status"),sa.CheckConstraint("max_deep_runs >= 1 AND max_deep_runs <= 15",name="ck_research_cycles_budget"));op.create_index("ix_research_cycles_gameweek_status","research_cycles",["gameweek","status"]);op.create_index("ix_research_cycles_gameweek","research_cycles",["gameweek"])
    op.create_table("research_cycle_players",sa.Column("id",sa.String(36),primary_key=True),sa.Column("cycle_id",sa.String(36),sa.ForeignKey("research_cycles.id",ondelete="CASCADE"),nullable=False),sa.Column("player_id",sa.Integer(),sa.ForeignKey("players.id",ondelete="RESTRICT"),nullable=False),sa.Column("watchlist_entry_id",sa.String(36),sa.ForeignKey("watchlist_entries.id",ondelete="SET NULL")),sa.Column("pulse_id",sa.String(36),sa.ForeignKey("player_gameweek_pulses.id",ondelete="SET NULL")),sa.Column("state",sa.String(16),nullable=False),sa.Column("selected_for_deep_research",sa.Boolean(),nullable=False),sa.Column("queue_rank",sa.Integer()),sa.Column("selection_reason",sa.JSON()),sa.Column("deep_run_id",sa.String(36),sa.ForeignKey("research_deep_runs.id",ondelete="SET NULL")),sa.Column("failure_reason",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("cycle_id","player_id",name="uq_research_cycle_player"),sa.CheckConstraint("state IN ('monitored','triggered','selected','deferred','researching','researched','failed')",name="ck_research_cycle_players_state"));op.create_index("ix_research_cycle_players_player_state","research_cycle_players",["player_id","state"]);op.create_index("ix_research_cycle_players_cycle_selected","research_cycle_players",["cycle_id","selected_for_deep_research"])
    op.create_table("research_cycle_player_triggers",sa.Column("cycle_player_id",sa.String(36),sa.ForeignKey("research_cycle_players.id",ondelete="CASCADE"),primary_key=True),sa.Column("research_trigger_id",sa.String(36),sa.ForeignKey("player_research_triggers.id",ondelete="RESTRICT"),primary_key=True))
def downgrade(): op.drop_table("research_cycle_player_triggers");op.drop_table("research_cycle_players");op.drop_table("research_cycles")
