"""add durable Match Center state

Revision ID: 0018_match_center
Revises: 0017_decision_center_foundation
"""
from alembic import op
import sqlalchemy as sa

revision = "0018_match_center"
down_revision = "0017_decision_center_foundation"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("fpl_match_center_snapshots", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("gameweek", sa.Integer(), nullable=False), sa.Column("status", sa.String(16), nullable=False), sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False), sa.Column("failure_reason", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("gameweek", name="uq_fpl_match_center_snapshot_gameweek"), sa.CheckConstraint("status IN ('available', 'partial', 'unavailable')", name="ck_fpl_match_center_snapshot_status")); op.create_index("ix_fpl_match_center_snapshots_gameweek", "fpl_match_center_snapshots", ["gameweek"])
    op.create_table("fpl_match_center_fixture_states", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("snapshot_id", sa.Integer(), sa.ForeignKey("fpl_match_center_snapshots.id", ondelete="CASCADE"), nullable=False), sa.Column("official_fixture_id", sa.Integer(), nullable=False), sa.Column("home_team_id", sa.Integer(), nullable=False), sa.Column("away_team_id", sa.Integer(), nullable=False), sa.Column("kickoff_time", sa.DateTime(timezone=True)), sa.Column("started", sa.Boolean(), nullable=False), sa.Column("finished", sa.Boolean(), nullable=False), sa.Column("finished_provisional", sa.Boolean()), sa.Column("fixture_minutes", sa.Integer()), sa.Column("home_score", sa.Integer()), sa.Column("away_score", sa.Integer()), sa.UniqueConstraint("snapshot_id", "official_fixture_id", name="uq_fpl_match_center_fixture")); op.create_index("ix_fpl_match_center_fixture_states_snapshot_id", "fpl_match_center_fixture_states", ["snapshot_id"]); op.create_index("ix_fpl_match_center_fixture_states_official_fixture_id", "fpl_match_center_fixture_states", ["official_fixture_id"])
    op.create_table("fpl_match_center_player_states", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("snapshot_id", sa.Integer(), sa.ForeignKey("fpl_match_center_snapshots.id", ondelete="CASCADE"), nullable=False), sa.Column("player_id", sa.Integer(), sa.ForeignKey("players.id", ondelete="RESTRICT"), nullable=False), sa.Column("total_points", sa.Integer(), nullable=False), sa.Column("minutes", sa.Integer()), sa.Column("goals_scored", sa.Integer()), sa.Column("assists", sa.Integer()), sa.Column("clean_sheets", sa.Integer()), sa.Column("goals_conceded", sa.Integer()), sa.Column("bonus", sa.Integer()), sa.Column("bps", sa.Integer()), sa.Column("expected_goals", sa.Float()), sa.Column("expected_assists", sa.Float()), sa.Column("expected_goal_involvements", sa.Float()), sa.Column("expected_goals_conceded", sa.Float()), sa.Column("raw_stats", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("snapshot_id", "player_id", name="uq_fpl_match_center_player")); op.create_index("ix_fpl_match_center_player_states_snapshot_id", "fpl_match_center_player_states", ["snapshot_id"]); op.create_index("ix_fpl_match_center_player_states_player_id", "fpl_match_center_player_states", ["player_id"])
    op.create_table("fpl_match_center_manager_states", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("snapshot_id", sa.Integer(), sa.ForeignKey("fpl_match_center_snapshots.id", ondelete="CASCADE"), nullable=False), sa.Column("manager_id", sa.Integer(), sa.ForeignKey("fpl_managers.id", ondelete="RESTRICT"), nullable=False), sa.Column("squad_snapshot_id", sa.Integer(), sa.ForeignKey("fpl_manager_gameweek_snapshots.id", ondelete="RESTRICT"), nullable=False), sa.Column("official_event_points", sa.Integer()), sa.Column("provisional_live_points", sa.Integer()), sa.Column("active_chip", sa.String(64)), sa.Column("automatic_subs", sa.JSON()), sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("snapshot_id", "manager_id", name="uq_fpl_match_center_manager")); op.create_index("ix_fpl_match_center_manager_states_snapshot_id", "fpl_match_center_manager_states", ["snapshot_id"]); op.create_index("ix_fpl_match_center_manager_states_manager_id", "fpl_match_center_manager_states", ["manager_id"])


def downgrade() -> None:
    op.drop_table("fpl_match_center_manager_states"); op.drop_table("fpl_match_center_player_states"); op.drop_table("fpl_match_center_fixture_states"); op.drop_table("fpl_match_center_snapshots")
