"""add durable decision analysis"""
from alembic import op
import sqlalchemy as sa

revision = "0023_decision_analysis"; down_revision = "0022_research_queue_indexes"; branch_labels = None; depends_on = None
def upgrade():
    op.create_table("decision_analysis_runs", sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("decision_sessions.id",ondelete="CASCADE"),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("research_cutoff",sa.DateTime(timezone=True),nullable=False),sa.Column("prompt_version",sa.String(64),nullable=False),sa.Column("recommended_option_id",sa.String(36),sa.ForeignKey("decision_options.id",ondelete="SET NULL")),sa.Column("outcome",sa.String(24),nullable=False),sa.Column("confidence",sa.String(16),nullable=False),sa.Column("executive_summary",sa.Text()),sa.Column("reasoning",sa.JSON()),sa.Column("key_tradeoffs",sa.JSON(),nullable=False),sa.Column("key_risks",sa.JSON(),nullable=False),sa.Column("contradictions",sa.JSON(),nullable=False),sa.Column("missing_information",sa.JSON(),nullable=False),sa.Column("what_could_change_decision",sa.JSON(),nullable=False),sa.Column("failure_reason",sa.Text()),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
    op.create_index("ix_decision_analysis_runs_session_status","decision_analysis_runs",["session_id","status"]); op.create_index("ix_decision_analysis_runs_recommended_option","decision_analysis_runs",["recommended_option_id"])
    op.create_table("decision_option_analyses",sa.Column("id",sa.String(36),primary_key=True),sa.Column("analysis_run_id",sa.String(36),sa.ForeignKey("decision_analysis_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("option_id",sa.String(36),sa.ForeignKey("decision_options.id",ondelete="CASCADE"),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("summary",sa.Text()),sa.Column("strengths",sa.JSON(),nullable=False),sa.Column("weaknesses",sa.JSON(),nullable=False),sa.Column("risks",sa.JSON(),nullable=False),sa.Column("research_gaps",sa.JSON(),nullable=False),sa.Column("exposure_change",sa.JSON()),sa.Column("squad_effect",sa.JSON()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("analysis_run_id","option_id",name="uq_decision_option_analysis")); op.create_index("ix_decision_option_analyses_run","decision_option_analyses",["analysis_run_id"])
    op.create_table("decision_analysis_player_contexts",sa.Column("id",sa.String(36),primary_key=True),sa.Column("analysis_run_id",sa.String(36),sa.ForeignKey("decision_analysis_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("player_id",sa.Integer(),sa.ForeignKey("players.id",ondelete="RESTRICT"),nullable=False),sa.Column("role",sa.String(24),nullable=False),sa.Column("synthesis_id",sa.String(36),sa.ForeignKey("research_player_syntheses.id",ondelete="SET NULL")),sa.Column("synthesis_cutoff",sa.DateTime(timezone=True)),sa.Column("overall_research_state",sa.String(16)),sa.Column("freshness_state",sa.String(16),nullable=False),sa.Column("research_gap_state",sa.String(16),nullable=False),sa.Column("research_gap_reasons",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("analysis_run_id","player_id","role",name="uq_decision_analysis_player_role")); op.create_index("ix_decision_analysis_player_context_run","decision_analysis_player_contexts",["analysis_run_id"]); op.create_index("ix_decision_analysis_player_context_player","decision_analysis_player_contexts",["player_id"])
def downgrade():
    op.drop_table("decision_analysis_player_contexts"); op.drop_table("decision_option_analyses"); op.drop_table("decision_analysis_runs")
