"""add durable gameweek selection decisions"""
from alembic import op
import sqlalchemy as sa
revision="0025_gameweek_selection_decisions"; down_revision="0024_decision_analysis_session_index"; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("gameweek_selections",sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("decision_sessions.id",ondelete="CASCADE"),nullable=False),sa.Column("starting_xi_player_ids",sa.JSON(),nullable=False),sa.Column("bench_player_ids",sa.JSON(),nullable=False),sa.Column("captain_player_id",sa.Integer(),sa.ForeignKey("players.id",ondelete="RESTRICT")),sa.Column("vice_captain_player_id",sa.Integer(),sa.ForeignKey("players.id",ondelete="RESTRICT")),sa.Column("finalized_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("session_id",name="uq_gameweek_selection_session")); op.create_index("ix_gameweek_selections_session_id","gameweek_selections",["session_id"])
    op.create_table("fpl_selection_analysis_runs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("decision_sessions.id",ondelete="CASCADE"),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("outcome",sa.String(24),nullable=False),sa.Column("research_cutoff",sa.DateTime(timezone=True),nullable=False),sa.Column("prompt_version",sa.String(64),nullable=False),sa.Column("recommended_starting_xi",sa.JSON(),nullable=False),sa.Column("recommended_bench_order",sa.JSON(),nullable=False),sa.Column("recommended_captain_player_id",sa.Integer()),sa.Column("recommended_vice_player_id",sa.Integer()),sa.Column("confidence",sa.String(16),nullable=False),sa.Column("executive_summary",sa.Text()),sa.Column("captaincy_reasoning",sa.Text()),sa.Column("lineup_reasoning",sa.Text()),sa.Column("bench_reasoning",sa.Text()),sa.Column("risks",sa.JSON(),nullable=False),sa.Column("contradictions",sa.JSON(),nullable=False),sa.Column("research_gaps",sa.JSON(),nullable=False),sa.Column("what_could_change_decision",sa.JSON(),nullable=False),sa.Column("reasoning",sa.JSON()),sa.Column("failure_reason",sa.Text()),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now())); op.create_index("ix_selection_analysis_session_status","fpl_selection_analysis_runs",["session_id","status"]); op.create_index("ix_fpl_selection_analysis_runs_session_id","fpl_selection_analysis_runs",["session_id"])
    op.create_table("selection_analysis_player_contexts",sa.Column("id",sa.String(36),primary_key=True),sa.Column("analysis_run_id",sa.String(36),sa.ForeignKey("fpl_selection_analysis_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("player_id",sa.Integer(),sa.ForeignKey("players.id",ondelete="RESTRICT"),nullable=False),sa.Column("synthesis_id",sa.String(36),sa.ForeignKey("research_player_syntheses.id",ondelete="SET NULL")),sa.Column("synthesis_cutoff",sa.DateTime(timezone=True)),sa.Column("research_state",sa.String(16)),sa.Column("research_gap_state",sa.String(16),nullable=False),sa.Column("relevant_dimension_facts",sa.JSON(),nullable=False),sa.UniqueConstraint("analysis_run_id","player_id",name="uq_selection_analysis_context_player")); op.create_index("ix_selection_analysis_player_contexts_analysis_run_id","selection_analysis_player_contexts",["analysis_run_id"])
def downgrade():
    op.drop_table("selection_analysis_player_contexts"); op.drop_table("fpl_selection_analysis_runs"); op.drop_table("gameweek_selections")
